### ISSUE TITLE
Allow to pass template as string

### ISSUE THREAD

**Issue by pascalberger** [mholo65/gazorator#4]
I'm looking at replacing RazorEngine in the Cake.Issues.Reporting.Generic addin with Gazorator to allow it to target .NET Standard (https://github.com/cake-contrib/Cake.Issues.Reporting.Generic/issues/3). For this I would need to pass in the template as a string instead of the path to a template file. 

Would it be possible to provide an overide of `ProcessAsync` (or another method) which accepts a string containing the content of the Razor template?

**Comment by bjorkstromm** [comment]
:+1: sounds like a great idea!

**Comment by bjorkstromm** [comment]
Fixed in 0.4.0
